ICFERApp/Models/Student.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ICFERApp.Models
{
    public class Student
    {
        [Key]
        public long Id { get; set; }

        private string _autogeneratedNumber;

        public  string StudentRegNo
        {
            get => _autogeneratedNumber;
            set
            {
                _autogeneratedNumber = value;
                _autogeneratedNumber = "BITI-" + Id + "-" + DateTime.Now.Year;
            }
        }

        [Display(Name="First Name")]
        [Required]
        public string FirstName { get; set; }
        [Display(Name="Middle Name")]
        [Required]
        public string MiddleName { get; set; }
        [Display(Name="Last Name")]
        [Required]
        public string LastName { get; set; }
        [Display(Name="Nationality")]
        [Required]
        public string Nationality { get; set; }
        [Display(Name="Gender")]
        [Required]
        public string Gender { get; set; }
        [Display(Name="Religion")]
        [Required]
        public string Religion { get; set; }
        [Display(Name="Medical Condition")]
        [Required]
        public string MedicalCondition { get; set; }
        [Display(Name="Deceased")]
        [Required]
        public string Deceased { get; set; }
        [Display(Name="Home Address")]
        [Required]
        public string HomeAddress { get; set; }
        [Display(Name="Country Of Residence")]
        [Required]
        public string CountryOfResidence { get; set; }
        [Display(Name="City")]
        [Required]
        public string City { get; set; }
        [Display(Name="Date Of Birth")]
        [Required]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}")]
        public DateTime DateOfBirth { get; set; }
        
        [Required]
        public int Age { get; set; }

        public string ImageUrl { get; set; }
        
        public ApplicationUser User { get; set; }
        public string UserId { get; set; }
        public string UserName { get; set; }


        public virtual Parents Parents { get; set; }
        public virtual Education Education { get; set; }
        public virtual Guardian Guardian { get; set; }
        public virtual Siblings Siblings { get; set; }
    }
}

ICFERApp/Controllers/ReportController.cs
using System.Threading.Tasks;
using ICFERApp.Repository;
using jsreport.AspNetCore;
using jsreport.Types;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NetBarcode;

namespace ICFERApp.Controllers
{
    public class ReportsController : Controller
    {
        
        private readonly IStudentRepository _studentRepository;
        public IJsReportMVCService JsReportMVCService { get; }
        
        public ReportsController(IStudentRepository studentRepository,IJsReportMVCService jsReportMVCService)
        {
            _studentRepository = studentRepository;
            JsReportMVCService = jsReportMVCService;
        }

        // GET
        [MiddlewareFilter(typeof(JsReportPipeline))]
        
        [Authorize]
        public async Task<IActionResult> ReportDetails(int id)
        {
            var singleStudent = _studentRepository.GetSingleStudent(id);
            var header = await JsReportMVCService.RenderViewToStringAsync(
                HttpContext, RouteData, "ReportDetails", singleStudent);
            
           
            var barcode = new Barcode(singleStudent.StudentRegNo, NetBarcode.Type.Code128, true);
            ViewBag.BarCode = barcode.GetBase64Image();
            HttpContext.JsReportFeature()
                .Recipe(Recipe.ChromePdf)
                .Configure((r) => r.Template.Chrome = new Chrome{ HeaderTemplate = header });
            
            
            return View(singleStudent);
        }
    }
}

ICFERApp/Controllers/StudentController.cs
using System;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using ICFERApp.Models;
using ICFERApp.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NetBarcode;
using NToastNotify;
using ReflectionIT.Mvc.Paging;
using X.PagedList;
using Type = System.Type;

namespace ICFERApp.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentRepository _studentRepository;
        private readonly IToastNotification _toastNotification;
        private readonly UserManager<ApplicationUser> _userManager;
        public StudentController(IStudentRepository studentRepository,
            IToastNotification toastNotification,
            UserManager<ApplicationUser> userManager 
            )
        {
            _studentRepository = studentRepository;
            _toastNotification = toastNotification;
            _userManager = userManager;
        }

        // GET
        [Authorize]
        public  IActionResult Index(string search ,int? pageNumber)
        {
            
            var nextPage = pageNumber ?? 1;
            
            
            if (!string.IsNullOrEmpty(search))
            {
                var foundStudents = _studentRepository.SearchStudents(search);
                var onePageOfFoundStudents = foundStudents.ToPagedList(nextPage, 3);
                ViewBag.onePageOfStudents = onePageOfFoundStudents;
                return View();
                
            }
            var students =  _studentRepository.GetAllStudents();
            var onePageOfStudents = students.ToPagedList(nextPage, 3);
            ViewBag.onePageOfStudents = onePageOfStudents;
                        
            return View();
        }

        [HttpGet]
        [Authorize]
        public IActionResult New()
        {
            ViewBag.IsEditMode = "false";
            var student = new Student();
            return View(student);
        }


        [HttpPost]
        [Authorize]
        public IActionResult New(Student student, string IsEditMode, IFormFile file)
        {

            if (!ModelState.IsValid)
            {
                ViewBag.IsEditMode = IsEditMode;
                return View(student);
            }

            try
            {

                if (IsEditMode.Equals("false"))
                {

                    var userId = _userManager.GetUserId(this.HttpContext.User);
                    var userName = _userManager.GetUserName(this.HttpContext.User);
                    
                    student.UserId = userId;
                    student.UserName = userName;
                    _studentRepository.Create(student);
                     UploadFile(file, student.Id);
                    _toastNotification.AddSuccessToastMessage("Student has been created successfully.");

                }

                else
                {
                    
                    var userId = _userManager.GetUserId(this.HttpContext.User);
                    var userName = _userManager.GetUserName(this.HttpContext.User);
                    
                    student.UserId = userId;
                    student.UserName = userName;

                    if (file == null)
                    {
                       
                       
                        _studentRepository.EditWithoutFile(student);
                        _toastNotification.AddSuccessToastMessage("Student has been edited successfully.");
                    }
                    else
                    {
                       
                        _studentRepository.Edit(student);
                        UploadFile(file, student.Id);
                        _toastNotification.AddSuccessToastMessage("Student has been edited successfully.");
                        
                    }

                }

                return RedirectToAction(nameof(Index));
            }
            catch (Exception e)
            {

                return RedirectToAction(nameof(Index));
            }

        }

        [Authorize]
        public IActionResult Edit(int id)
        {

            try
            {

                ViewBag.IsEditMode = "true";

                var student = _studentRepository.GetSingleStudent(id);

                return View("New", student);
            }
            catch (Exception ex)
            {
                return Content("Could not find Pet");
            }

        }
        
        [Authorize]
        public void UploadFile(IFormFile file, long studentId)
        {
            var fileName = file.FileName;
            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/images",fileName);

            using (var fileStream = new FileStream(path, FileMode.Create))
            {
                file.CopyTo(fileStream);
            }

            var student = _studentRepository.GetSingleStudent(studentId);
            student.ImageUrl = fileName;
            _studentRepository.Edit(student);
        }

        [Authorize]
        public IActionResult Delete(int id)
        {
            try
            {
                var pet = _studentRepository.GetSingleStudent(id);
                _studentRepository.Delete(pet);
                _toastNotification.AddSuccessToastMessage("Student has been deleted successfully.");

                return RedirectToAction(nameof(Index));

            }
            catch (Exception e)
            {

                return BadRequest();
            }


        }

        [Authorize]
        public IActionResult Details(long id)
        {
            var singleStudent = _studentRepository.GetSingleStudent(id);
            
            var barcode = new Barcode(singleStudent.StudentRegNo, NetBarcode.Type.Code128, true);
            ViewBag.BarCode = barcode.GetBase64Image();
            
            return View(singleStudent);
        }

        [Authorize]
        public IActionResult BiometricSearch()
        {

            return View();
        }


        
    }
}

ICFERApp/Views/Student/BiometricSearch.cshtml
@model Student

<h2> Coming soon.</h2>

ICFERApp/Views/Student/Details.cshtml
@model Student

<a asp-action="Index" asp-controller="Student" 
   class="btn btn-danger"> < Back </a>

<a asp-route-id="@Model.Id" asp-action="ReportDetails" asp-controller="Reports" 
    class="btn btn-primary">Print Report</a>

<br/>
<br/>

<style>
    .centerTable { margin: 0px auto; }
</style>

@* Styling Student's Report. *@

<h2 class="text-center" style="color: rgb(21, 121, 31)">Student Details</h2>
<div class="card">
    <div class="card-body">
    <table cellpadding="0" cellspacing="0" class="centerTable">
          
        <tr>
            <td>
                <div class="pv-lg"><img  height="200" width="130" src="/images/@Model.ImageUrl" alt="Contact"></div>

            </td>
            <td> <h5>Registration Number :</h5>  <i> <h5 style="color: rgb(21, 121, 31)">@Model.StudentRegNo</h5> </i></td>
        </tr>
        <tr>
            <td>
                <br/>
                <br/>
            </td>
        </tr>
        <tr>
            <td>
                <img height="80" width="150" src="data:image/png;base64,  @ViewBag.BarCode" alt="Red dot" />
                <br/>
                <br/>
            </td>
        </tr>
            <tr>
                <td class="text-center" style="color: rgba(113, 3, 138, 0.99)"><h5>Student's Profile</h5></td>
            </tr>
        <tr>
            <td> <b>First Name:</b> @Model.FirstName   </td> 
            <td> <b>Middle Name :</b> @Model.MiddleName</td>
        </tr>
        
        <tr>
            <td> <b>Last Name :</b> @Model.LastName </td>
        </tr>
        <tr>
            <td><b>Age :</b> @Model.Age</td>
            <td> <b>Country :</b> @Model.Nationality</td>
        </tr>

        <tr>

            </tr>
            <tr>
                <td>
                    <b>Gender :</b> @Model.Gender
                </td>
                <td> <b>Religion :</b> @Model.Religion</td>
            </tr>

            <tr>
                <td> <b>Home Address :</b> @Model.HomeAddress</td>
                <td> <b>Country of Residence:</b> @Model.CountryOfResidence</td>
            </tr>

            <tr>
                <td> <b>Country of Residence:</b> @Model.CountryOfResidence</td>
                <td> <b>City :</b> @Model.City</td>
            </tr>

            <tr>
                <td> <b>Date of Birth :</b> @Model.DateOfBirth.ToShortDateString()</td>
                <td> <b>Medical Condition :</b> @Model.MedicalCondition</td>
            </tr>
            <tr>
                <td>
                    <br/>
                    <br/>
                </td>
            </tr>
            <tr>
                <td class="text-center" style="color: rgba(113, 3, 138, 0.99)"><h5>Education</h5></td>
            </tr>

            <tr>
                <td> <b>Education Level : </b> @Model.Education.EducationLevel</td>
                <td> <b>School :</b> @Model.Education.School</td>
            </tr>

            <tr>
                <td> <b>Address of School :</b> @Model.Education.AddressOfSchool</td>
                <td> <b>Home Address :</b> @Model.HomeAddress</td>
            </tr>

            <tr>
                <td> <b>Head Teacher:</b> @Model.Education.HeadTeacher</td>
                <td> <b>Telephone :</b> @Model.Education.Telephone</td>
            </tr>
            <tr>
                <td>
                    <br/>
                    <br/>
                </td>
            </tr>
            <tr>
                <td class="text-center"><h5 style="color: rgba(113, 3, 138, 0.99)">Parents Details.</h5></td>
            </tr>

            <tr>
                <td><b>Religion Of Deceased Father :</b> @Model.Parents.ReligionOfDeceasedFather</td>
                <td> <b>Religion Of Deceased Mother :</b> @Model.Parents.ReligionOfDeceasedMother</td>
            </tr>
            <tr>
                <td> <b>Date Of Demise Father :</b> @Model.Parents.DateOfDemiseOfFather.ToShortDateString()</td>
                <td> <b>Date Of Demise Mother :</b> @Model.Parents.DateOfDemiseOfMother.ToShortDateString()</td>
            </tr>
            <tr>
                <td> <b> Names of Mother :</b> @Model.Parents.NamesOfMother</td>
                <td> <b>Names of Father :</b> @Model.Parents.NamesOfFather</td>
            </tr>
            <tr>
                <td> <b>Religion of Mother :</b> @Model.Parents.ReligionOfMother</td>
                <td> <b>Marital Status of Mother :</b> @Model.Parents.MaritalStatusOfMother</td>
            </tr>
        <tr>
            <td> <b>Occupation of Mother :</b> @Model.Parents.OccupationOfMother</td>
            <td> <b>Monthly Income :</b> @Model.Parents.MonthlyIncome</td>
        </tr>
            <tr>
                <td>
                    <br/>
                    <br/>
                </td>
            </tr>
            <tr>
                <td class="text-center"><h5 style="color: rgba(113, 3, 138, 0.99)">Guardians Details.</h5></td>
            </tr>
            <tr>
                <td> <b>First Name:</b> @Model.Guardian.FirstName</td>
                <td> <b>Middle Name :</b> @Model.Guardian.MiddleName</td>
            </tr>

            <tr>
                <td> <b>Last Name :</b> @Model.Guardian.LastName</td>
                <td> <b>Relationship to Orphan :</b> @Model.Guardian.RelationshipToOrphan</td>
            </tr>

            <tr>
                <td> <b>Occupation:</b> @Model.Guardian.Occupation</td>
                <td> <b>Monthly Income :</b> @Model.Guardian.MonthlyIncome</td>
            </tr>

            <tr>
                <td><b> Employer's Name:</b> @Model.Guardian.EmployersName</td>
                <td><b>Worker's Address :</b> @Model.Guardian.WorkAddress</td>
            </tr>

            <tr>
                <td> <b>Mobile Number:</b> @Model.Guardian.MobileNo</td>
                <td> <b>Physical Location :</b> @Model.Guardian.PhysicalLocation</td>
            </tr>

        <tr>
            <td> <b>Comments :</b> @Model.Guardian.Comments</td>
        </tr>
            <tr>
                <td>
                    <br/>
                    <br/>
                </td>
            </tr>
            <tr>
                <td class="text-center" style="color: rgba(113, 3, 138, 0.99)"><h5>Siblings Information</h5></td>
            </tr>
                <tr>
                    <td> <b>Number of Brothers :</b> @Model.Siblings.NumberOfBrothers</td>
                    <td> <b>Number of Sisters :</b> @Model.Siblings.NumberOfSisters</td>
        </tr>   
         
    </table>
  </div>
</div>

ICFERApp/Views/Student/Index.cshtml
 @using X.PagedList;
 @using X.PagedList.Mvc.Core;
 @using X.PagedList.Mvc.Common;

 <html>
 <head>
    
 </head>
 <body>
 
    <a class="btn btn-info" asp-action="New">Add New Student</a>
    <br/>
    <br/>

 <form asp-action="Index" asp-controller-="POST">
     <div class="row input-group">
         <input type="text" name="search" id="search" class="form-control"/>
         <div class="input-group-btn">
             <input type="submit" value="Search" class="btn btn-primary"/>
         </div>
     </div>
 </form>
 @if (@ViewBag.onePageOfStudents.Count != 0)
 {
    <table class="table table-striped">
        <thead class="thead-dark">
        <tr>
            <td ><b>Reg No.</b></td>
            <td ><b>Student Photo</b></td>
            <td><b>FirstName</b></td>
            <td><b>MiddleName</b></td>
            <td><b>LastName</b></td>
            <td><b>Nationality</b></td>
            <td><b>Gender</b></td>
            <td colspan="2"> <b>Actions</b></td>
        </tr>
        </thead>
        <tbody>
        @foreach (var student in ViewBag.onePageOfStudents)
        {
            <tr>
                <td>@student.StudentRegNo</td>
                <td>
                    <div class="thumbnail">
                        <img src="/images/@student.ImageUrl" width="90" height="90"/>
                    </div>
                </td>
                <td>@student.FirstName</td>
                <td>@student.MiddleName</td>
                <td>@student.LastName</td>
                <td>@student.Nationality</td>
                <td>@student.Gender</td>
                <d>
                    <td>
                        <a class="btn btn-warning" asp-action="Details" asp-controller="Student" asp-route-Id="@student.Id">Details</a>
                    </td>
                    <td>
                        <a class="btn btn-primary" asp-action="edit" asp-route-Id="@student.Id">Edit</a>
                    </td>
                    <td>
                        <a
                            class="btn btn-danger delete"
                            asp-route-Id="@student.Id"
                            asp-action="Delete">
                            Delete
                        </a>
                    </td>
                </d>
            </tr>
        }
        </tbody>
    </table>
}
else
{
    <h5 class="text-center">Sorry,there's no student available with this search,please try again.</h5>
}

 <div class="pagination">
     <div class="col-md12">
         
         @Html.PagedListPager((IPagedList)ViewBag.onePageOfStudents,pageNumber=>Url.Action("Index",new { pageNumber }),
             new X.PagedList.Mvc.Common.PagedListRenderOptionsBase
             {
                 LiElementClasses = new string[] { "page-item" },
                 PageClasses = new string[] { "page-link" }
             })
     </div>

 </div>
 
 </body>
 
 </html>